// This file is part of GNOME Games. License: GPLv3

errordomain Games.SegaSaturnError {
	INVALID_CUE_SHEET,
	INVALID_FILE_TYPE,
	CANT_READ_FILE,
	INVALID_SIZE,
	INVALID_HEADER,
	INVALID_DATE,
	INVALID_DISK_INFO,
}
